### ISSUE TITLE
Feature Request: Manage Clock from token

### ISSUE THREAD

**Issue by pesky-wobbit** [Argonius-Angelus/lancer-clocks#4]
I would like to be able to close the window open during play.
Perhaps a change in token HP is reflected in the clock?
Even better would be buttons in the token HUD that lets you do everything the sheet does.

**Comment by Argonius-Angelus** [comment]
I have tried to implement these, but have come across multiple issues with implementation.
1. There is no "required standard" for HP value storage. As a result, adding this sort of functionality would very likely cause issues as I would have to try and account for every game system. Also, due to the lack of this required standard in systems, it is very difficult to implement something like this and still say that it's still system agnostic.
2. I have had zero luck getting extra buttons on the token HUD working as requested. The main issue I am experiencing is getting them to reliably render and activate. This is very likely due to a lack of experience on my end in regards to this, and as a result I have tabled this feature until I attain more knowledge in this regard.

Also, I am unsure what you mean by "I would like to be able to close the window open during play." Could you give some examples of what you mean?

**Comment by pesky-wobbit** [comment]
Thanks for your response!
My inability to close the window was due to my own numskulledness - other modules in the title bar were pushing the Close button out of view.
Thanks again.
